---
- name: Deploy Kyverno MVP stand
  hosts: vm
  become: true
  gather_facts: true

  roles:
  - { role: prereqs, tags: ['prereqs'] }
  - { role: docker, tags: ['docker'] }
  - { role: kubectl, tags: ['kubectl'] }
  - { role: kind, tags: ['kind'] }
  - { role: ingress, tags: ['ingress'] }
  - { role: argocd, tags: ['argocd'] }
  - { role: kyverno, tags: ['kyverno'] }
  - { role: monitoring, tags: ['monitoring'] } 