apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-non-root
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: non-root
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Container must not run as root (runAsNonRoot must be true)."
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true